{% set name = "pnpm" %}
{% set version = "8.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9d22f8bfa64d4fb14dfd29a51c0e3ae34055f11c312f19baf5751b000bd305a9

build:
  # https://github.com/conda-forge/pnpm-feedstock/issues/31
  skip: true  # [win]
  number: 0

requirements:
  build:
    - nodejs >=16
  host:
    - nodejs >=16
  run:
    - nodejs >=16

test:
  commands:
    - pnpm --help

about:
  home: https://github.com/pnpm/pnpm
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 📦🚀 Fast, disk space efficient package manager

extra:
  recipe-maintainers:
    - xhochy
    - pavelzw
    - JannikWibkerQC
