{% set name = "pnpm" %}
{% set version = "7.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 17cd4a23092cf8bed3ac2feb9cad2af9079cc068fcf37164d403ff76cf9f280e

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - pnpm --help

about:
  home: https://github.com/pnpm/pnpm
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 📦🚀 Fast, disk space efficient package manager

extra:
  recipe-maintainers:
    - xhochy
    - pavelzw
