{% set name = "pnpm" %}
{% set version = "8.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e28d1cf75a172e40c7ff7031dd72cec0c7fc0908a2ca3b9f50b56cd7708d2083

build:
  # https://github.com/conda-forge/pnpm-feedstock/issues/31
  skip: true  # [win]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - nodejs
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - pnpm --help

about:
  home: https://github.com/pnpm/pnpm
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 📦🚀 Fast, disk space efficient package manager

extra:
  recipe-maintainers:
    - xhochy
    - pavelzw
    - JannikWibkerQC
