{% set name = "pnpm" %}
{% set version = "10.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7ea54057df27f41d3356a79bf684ebaaeb0e7ec320c6973c6b70f0c2a3f4c794

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - nodejs
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - pnpm --help

about:
  home: https://github.com/pnpm/pnpm
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 📦🚀 Fast, disk space efficient package manager

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - xhochy
    - pavelzw
