schema_version: 1

context:
  name: pnpm
  version: "11.7.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name }}/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2b23ef51222aa371dc0f53e9e07a8cf4dc8431c08dc8a5ac82f289e1add6f105

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - make
    - nodejs
    - if: win
      then:
        - m2-sed
      else:
        - sed
  host:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - pnpm --help
  - package_contents:
      bin:
        - if: unix
          then:
            - pn
            - pnpx
            - pnx
        - pnpm
      files:
        - if: unix
          then:
            - lib/node_modules/pnpm/*
          else:
            - Library/share/pnpm/*
      strict: true

about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 📦🚀 Fast, disk space efficient package manager
  homepage: https://github.com/pnpm/pnpm

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - xhochy
    - pavelzw
