schema_version: 1

context:
  name: pnpm
  version: "11.21.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name }}/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 303ba2d3a5bc88153e165be3b6ef9f3f1647d6c46465363b8850620499f15d57

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - make
    - nodejs
    - if: win
      then:
        - m2-sed
      else:
        - sed
  host:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - pnpm --help
  - package_contents:
      bin:
        - if: unix
          then:
            - pn
            - pnpx
            - pnx
        - pnpm
      files:
        - if: unix
          then:
            - lib/node_modules/pnpm/*
          else:
            - Library/share/pnpm/*
      strict: true

about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 📦🚀 Fast, disk space efficient package manager
  homepage: https://github.com/pnpm/pnpm

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - xhochy
    - pavelzw
