schema_version: 1

context:
  name: pnpm
  version: "10.33.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name }}/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c8082e6ab40c243f033e561a9cc90934d69cfc128f9a4fff2d66b11db575636e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - make
    - nodejs
    - if: win
      then:
        - m2-sed
      else:
        - sed
  host:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - pnpm --help

about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 📦🚀 Fast, disk space efficient package manager
  homepage: https://github.com/pnpm/pnpm

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - xhochy
    - pavelzw
