schema_version: 1

context:
  name: pnpm
  version: "10.21.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name }}/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ad8296037ed89d7ca28e2e4d5483b14eb385b076e66337170346df9ef6d90f2b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - make
    - nodejs
    - if: win
      then:
        - m2-sed
      else:
        - sed
  host:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - pnpm --help

about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 📦🚀 Fast, disk space efficient package manager
  homepage: https://github.com/pnpm/pnpm

extra:
  recipe-maintainers:
    - JaninaWibkerQC
    - xhochy
    - pavelzw
